src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length:32)]
    private ?string $name = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column]
    private ?bool $is_active = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable:true)]
    private ?\DateTimeInterface $modified_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getModifiedAt(): ?\DateTimeInterface
    {
        return $this->modified_at;
    }

    public function setModifiedAt(?\DateTimeInterface $modified_at): static
    {
        $this->modified_at = $modified_at;

        return $this;
    }
}

src/Form/UserForm.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class UserForm
 */
class UserForm extends AbstractType {

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     * @return void
     */
    public function buildForm(FormBuilderInterface $builder, array $options) {

        $builder
            ->add('name', TextType::class, ['label' => 'Felhasználónév', 'required' => false, 'attr' => ['class' => 'form-control', 'placeholder' => 'Felhasználónév']])
            ->add('password', PasswordType::class, ['label' => 'Jelszó', 'required' => false, 'attr' => ['class' => 'form-control', 'placeholder' => 'Jelszó']])
            ->add('submit', SubmitType::class, ['label' => 'Belépés', 'attr' => ['class' => 'btn btn-primary']]);
    }

    /**
     * @param OptionsResolver $resolver
     * @return void
     */
    public function configureOptions(OptionsResolver $resolver) {

        $resolver->setDefaults([
            'data_class' => User::class
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Constant\Project;
use App\Entity\User;
use App\Form\AddUserForm;
use App\Form\EditUserForm;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Monolog\DateTimeImmutable;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class UserController
 */
class UserController extends AbstractController {

    /**
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    #[Route('/users', name: 'users', methods: 'GET')]
    public function user(EntityManagerInterface $entityManager): Response {

        $users = array();

        try {
            $users = $entityManager->getRepository(User::class)->findAll();
        } catch (Exception $e) {
            $this->addFlash('error', $e->getMessage());
        }

        return $this->render('User/user.html.twig', ['form' => $users]);
    }

    /**
     * Új felhasználó rögzítése
     *
     * @param Request $request
     * @param UserPasswordHasherInterface $passwordHasher
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    #[Route('/add-user', name: 'addUser', methods: ['POST', 'GET'])]
    public function addUser(Request                     $request,
                            UserPasswordHasherInterface $passwordHasher,
                            EntityManagerInterface      $entityManager): Response {

        $user = new User();
        $form = $this->createForm(AddUserForm::class, $user);

        try {
            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                $formData = $form->getData();

                if(empty($formData->getName()) || empty($formData->getEmail())) {
                    throw new Exception(Project::EMPTY_FIELD_ERROR_MSG);
                } else {
                    date_default_timezone_set('Europe/Budapest');
                    $hashedPassword = $passwordHasher->hashPassword($user, $formData->getPassword());
                    $user->setName($formData->getName());
                    $user->setEmail($formData->getEmail());
                    $user->setRoles($formData->getRoles());
                    $user->setPassword($hashedPassword);
                    $user->setIsActive(Project::IS_ACTIVE);
                    $user->setCreatedAt(new DateTimeImmutable(date('Y-m-d H:i:s')));
                    $entityManager->persist($user);
                    $entityManager->flush();
                    $this->addFlash('success', Project::USER_SUCCESSFUL_MSG);
                }
            }
        } catch (Exception $e) {
            $this->addFlash('error', $e->getMessage());
        }

        return $this->render('User/newUser.html.twig', ['form' => $form]);
    }

    /**
     * Felhasználó módosítása
     *
     * @param Request $request
     * @param int $userId
     * @param UserPasswordHasherInterface $passwordHasher
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    #[Route('/edit-user/{userId}', name: 'editUser', methods: ['GET', 'POST'])]
    public function editUser(Request                     $request,
                             int                         $userId,
                             UserPasswordHasherInterface $passwordHasher,
                             EntityManagerInterface      $entityManager): Response {

        $user = new User();
        $form = $this->createForm(EditUserForm::class, $user);

        try {
            $criteria = array('id' => $userId);
            $userData = $entityManager->getRepository(User::class)->findOneBy($criteria);

            if(empty($userData)) {
                throw new Exception(Project::INVALID_PARAMETER_ERROR_MSG);
            } else {
                $form = $this->createForm(EditUserForm::class, $userData);
                $form->handleRequest($request);
                if ($form->isSubmitted() && $form->isValid()) {
                    date_default_timezone_set('Europe/Budapest');
                    $userData->setName($userData->getName());
                    $userData->setIsActive($userData->isIsActive());
                    $userData->setModifiedAt(new DateTimeImmutable(date('Y-m-d H:i:s')));
                    $entityManager->persist($userData);
                    $entityManager->flush();
                    $this->addFlash('success', Project::EDIT_SUCCESSFUL_MSG);
                }
            }
        } catch (Exception $e) {
            $this->addFlash('error', $e->getMessage());
        }

        return $this->render('User/editUser.html.twig', ['form' => $form]);
    }

    /**
     * Felhasználó törlése
     *
     * @param int $userId
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    #[Route('/delete-user/{userId}', name: 'deleteUser', methods: ['GET'])]
    public function deleteUser(int                    $userId,
                               EntityManagerInterface $entityManager): Response {

        $users = array();

        try {
            $criteria = array('id' => $userId);
            $userData = $entityManager->getRepository(User::class)->findOneBy($criteria);

            if(empty($userData)) {
                throw new Exception(Project::INVALID_PARAMETER_ERROR_MSG);
            } else {
                $entityManager->remove($userData);
                $entityManager->flush();
            }

            $users = $entityManager->getRepository(User::class)->findAll();
        } catch (Exception $e) {
            $this->addFlash('error', $e->getMessage());
        }

        return $this->render('User/user.html.twig', ['form' => $users]);
    }
}

templates/User/editUser.html.twig
{% extends 'base.html.twig' %}

{% block title %}Admin felület{% endblock %}

{% block body %}
    {{ form_start(form)}}
    <div class="col-lg-6 offset-lg-3">

        <div class="mb-3 row">
            <div class="col-md-12 text-center admin-line">
                <h2 class="logout-title">Admin felület</h2>
                <a href="/users" class="btn btn-primary logout-button">Vissza</a>
            </div>
        </div>

        <div class="mb-3 row">
            <div class="col-md-12 text-center">
                <h3>Felhasználó módosítása</h3>
            </div>
        </div>

        <div class="mb-4 row">
            {% for label, messages in app.flashes(['error', 'success']) %}
                {% for message in messages %}
                    <div class="confirmation-container col-md-12 text-center">
                        {% if label == "success" %}
                            <span class="confirmation">{{ message }}</span>
                        {% else %}
                            <span class="error">{{ message }}</span>
                        {% endif %}
                    </div>
                {% endfor %}
            {% endfor %}
        </div>

        <div class="mb-4 row">
            <div class="col-md-6 offset-md-3">
                {{ form_errors(form) }}
            </div>
        </div>

        <div class="mb-4 row">
            <div class="col-md-4 offset-md-4">
                {{ form_row(form.name) }}
            </div>
        </div>

        <div class="mb-4 row">
            <div class="col-md-4 offset-md-4">
                {{ form_row(form.email) }}
            </div>
        </div>

        <div class="mb-4 row">
            <div class="col-md-4 offset-md-4">
                {{ form_row(form.isActive) }}
            </div>
        </div>

        <div class="mb-4 row">
            <div class="col-md-4 offset-md-4">
                {{ form_row(form.createdAt) }}
            </div>
        </div>

        <div class="mb-4 row">
            <div class="col-md-12 text-center">
                {{ form_row(form.submit) }}
            </div>
        </div>

    </div>
    {{ form_end(form) }}
{% endblock %}

templates/User/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bejelentkezés{% endblock %}

{% block body %}
    {{ form_start(form)}}
        <div class="col-lg-6 offset-lg-3">

            <div class="mb-3 row">
                <div class="col-md-12 text-center">
                    <h2>Bejelentkezés</h2>
                </div>
            </div>

            <div class="mb-4 row">
                {% for label, messages in app.flashes(['error', 'success']) %}
                    {% for message in messages %}
                        <div class="confirmation-container col-md-12 text-center">
                            {% if label == "error" %}
                                <span class="error">{{ message }}</span>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>

            <div class="mb-4 row">
                <div class="col-md-6 offset-md-3">
                    {{ form_errors(form) }}
                </div>
            </div>

            <div class="mb-4 row">
                <div class="col-md-4 offset-md-4">
                    {{ form_row(form._username) }}
                </div>
            </div>
            <div class="mb-4 row">
                <div class="col-md-4 offset-md-4">
                    {{ form_row(form._password) }}
                </div>
            </div>

            <div class="mb-4 row">
                <div class="col-md-12 text-center">
                    {{ form_row(form.submit) }}
                </div>
            </div>

        </div>
    {{ form_end(form) }}
{% endblock %}

templates/User/newUser.html.twig
{% extends 'base.html.twig' %}

{% block title %}Admin felület{% endblock %}

{% block body %}
    {{ form_start(form)}}
    <div class="col-lg-6 offset-lg-3">

        <div class="mb-3 row">
            <div class="col-md-12 text-center admin-line">
                <h2 class="logout-title">Admin felület</h2>
                <a href="/users" class="btn btn-primary logout-button">Vissza</a>
            </div>
        </div>

        <div class="mb-3 row">
            <div class="col-md-12 text-center">
                <h3>Új felhasználó felvétele</h3>
            </div>
        </div>

        <div class="mb-4 row">
            {% for label, messages in app.flashes(['error', 'success']) %}
                {% for message in messages %}
                    <div class="confirmation-container col-md-12 text-center">
                        {% if label == "success" %}
                            <span class="confirmation">{{ message }}</span>
                        {% else %}
                            <span class="error">{{ message }}</span>
                        {% endif %}
                    </div>
                {% endfor %}
            {% endfor %}
        </div>

        <div class="mb-4 row">
            <div class="col-md-6 offset-md-3">
                {{ form_errors(form) }}
            </div>
        </div>

        <div class="mb-4 row">
            <div class="col-md-4 offset-md-4">
                {{ form_row(form.name) }}
            </div>
        </div>

        <div class="mb-4 row">
            <div class="col-md-4 offset-md-4">
                {{ form_row(form.email) }}
            </div>
        </div>

        <div class="mb-4 row">
            <div class="col-md-4 offset-md-4">
                {{ form_row(form.password) }}
            </div>
        </div>

        <div class="mb-4 row">
            <div class="col-md-12 text-center">
                {{ form_row(form.submit) }}
            </div>
        </div>

    </div>
    {{ form_end(form) }}
{% endblock %}

templates/User/user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Belépve{% endblock %}

{% block body %}
    <div class="col-lg-6 offset-lg-3">

        <div class="mb-3 row">
            <div class="col-md-12 text-center admin-line">
                <h2 class="logout-title">Admin felület</h2>
                <a href="/logout" class="btn btn-primary logout-button">Kijelentkezés</a>
            </div>
        </div>

        <div class="mb-3 row">
            <div class="col-md-12">
                <a href="/contacts" class="btn btn-secondary">Üzenetek</a>
                <a href="/users" class="btn btn-primary">Felhasználók</a>
            </div>
        </div>

        <div class="mb-3 row">
            <div class="col-md-12 text-center">
                <h3>Felhasználók</h3>
            </div>
        </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Név</th>
                    <th>E-mail cím</th>
                    <th>Státusz</th>
                    <th>Létrehozás dátuma</th>
                    <th>Műveletek</th>
                </tr>
            </thead>
            <tbody>
            {% for item in form %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.name }}</td>
                    <td>{{ item.email }}</td>
                    {% if item.isActive == true %}
                        <td>Aktív</td>
                    {% else %}
                        <td>Inaktív</td>
                    {% endif %}
                    <td>{{ item.createdAt|date('Y-m-d H:i:s') }}</td>
                    <td>
                        <a href="/edit-user/{{ item.id }}" class="btn btn-primary oparational-button edit-button">Szerkesztés</a>
                        <button type="button" class="btn btn-primary oparational-button btn-danger delete-button" data-bs-toggle="modal" data-bs-target="#deleteModal" id="{{ item.id }}">Törlés</button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="/add-user" class="btn btn-primary new-user-button">Új felhasználó felvétele</a>

    </div>


    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Törlés megerősítése</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Biztos, hogy törölni szeretné ezt az elemet?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Mégsem</button>
                    <a href="" class="btn btn-danger oparational-button" id="delete-button">Törlés</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}